services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      cluster:
        ipv4_address: 192.168.0.5

  management1:
    image: mysql/mysql-cluster
    command: ndb_mgmd
    networks:
      cluster:
        ipv4_address: 192.168.0.2

  ndb1:
    image: mysql/mysql-cluster
    command: ndbd
    networks:
      cluster:
        ipv4_address: 192.168.0.3

  ndb2:
    image: mysql/mysql-cluster
    command: ndbd
    networks:
      cluster:
        ipv4_address: 192.168.0.4

  mysql1:
    image: mysql/mysql-cluster
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: nicolas
    networks:
      cluster:
        ipv4_address: 192.168.0.10

networks:
  cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
