services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      cluster:
        ipv4_address: 192.168.0.5


  management1:
    image: mysql/mysql-cluster
    command: ndb_mgmd
    networks:
      cluster:
        ipv4_address: 192.168.0.2

  ndb1:
    image: mysql/mysql-cluster
    command: ndbd
    networks:
      cluster:
        ipv4_address: 192.168.0.3

  ndb2:
    image: mysql/mysql-cluster
    command: ndbd
    networks:
      cluster:
        ipv4_address: 192.168.0.4

  mysql1:
    image: mysql/mysql-cluster
      #entrypoint:
      #- "mysql -u root -pnicolas db < /sql_script.sql"
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: nicolas
      MYSQL_DATABASE: db
    networks:
      cluster:
        ipv4_address: 192.168.0.10
    volumes:
      - ./sql_script.sql:/docker-entrypoint-initdb.d/sql_script.sql
      - ./privileges.sql:/docker-entrypoint-initdb.d/privileges.sql


networks:
  cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
