apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://192.168.0.7:9090
    isDefault: true
  - name: MySQL
    type: mysql
    url: 192.168.0.10:3306
    user: root
    jsonData:
      database: db 
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
    secureJsonData:
      password: nicolas
