scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'mysql'
    #    params:
    #  auth_module: [client]
    scrape_interval: 5s

    static_configs:
      - targets: ['mysql-exporter:9104']
